routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\KaryawanController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['auth','CheckRole:1']], function(){
    Route::get('/post/trashed',[PostController::class, 'trashed'])->name('post.trashed');
    Route::get('/post/restore/{id}',[PostController::class, 'restore'])->name('post.restore');
    Route::delete('/post/kill/{id}',[PostController::class, 'kill'])->name('post.kill');
    

    Route::resource('user', UserController::class);
    Route::resource('karyawan', KaryawanController::class);
    Route::post('/karyawan/images',[KaryawanController::class, 'image_upload'])->name('karyawan.image_upload');

});

Route::group(['middleware' => ['auth','CheckRole:1,2,3']], function(){
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::resources([
        'post' => PostController::class,
        'tag' => TagController::class,
        'category' => CategoryController::class,
    ]);
});


Route::get('/',[BlogController::class, 'index']);
Route::get('/berita-sejahtera',[BlogController::class, 'berita'])->name('berita.utama') ;
Route::get('/berita-sejahtera/list/{category}',[BlogController::class, 'category_berita'])->name('berita.category');
Route::get('/berita-sejahtera/search',[BlogController::class, 'search_berita'])->name('berita.search');
Route::get('/berita-sejahtera/{slug}',[BlogController::class, 'isi_berita'])->name('berita.isi');

app/Models/Posts.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Posts extends Model
{
    use SoftDeletes;
    protected $fillable = ['judul','category_id','content','gambar','slug', 'user_id','status'];
    protected $table = 'posts';

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
    public function tags()
    {
        return $this->belongsToMany(Tags::class);
    }
    public function users()
    {
        return $this->belongsTo(User::class, 'user_id','id');
    }

    use HasFactory;
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;
use App\Models\Posts;
use App\Models\Category;
use App\Models\Tags;
use Illuminate\Support\Facades\Auth;
use illuminate\Support\Str;

use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Posts $post)
    {
        $post = $post->latest()->paginate(6);
        return view('post.index', compact('post'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = Category::all();
        $tags = Tags::all();
        return view('post.create', compact('category','tags'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->all());
        $this->validate($request,[
            'judul' => 'required',
            'category_id' => 'required',
            'content' => 'required',
            'gambar' => 'required',
            'status' => 'sometimes|boolean',
        ]);

        $gambar = $request->gambar;
        $new_gambar = time().$gambar->getClientOriginalName();
        if ($request->status == null) {
            $request->status = '0';
        }
        

        $post = Posts::create([
            'judul'=> $request->judul,
            'category_id'=> $request->category_id,
            'content'=> $request->content,
            'gambar'=> 'public/uploads/posts/'.$new_gambar,
            'slug'=> Str::slug($request->judul),
            'user_id' => Auth::id(),
            'status' => $request->status,
        ]);
        
        $post->tags()->attach($request->tags);

        $gambar->move('public/uploads/posts/',$new_gambar);
        return redirect()->route('post.index')->with('status','Artikel Berhasil Ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::all();
        $tags = Tags::all();
        $post = Posts::findorfail($id);
        return view('post.edit', compact('post','tags','category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'judul' => 'required',
            'category_id' => 'required',
            'content' => 'required',
            'status' => 'sometimes|boolean',
        ]);

        $post = Posts::findorfail($id);

        if($request->has('gambar')) {
            $gambar = $request->gambar;
            $new_gambar = time().$gambar->getClientOriginalName();
            $gambar->move('public/uploads/posts/',$new_gambar);

            $post_data = [
                'judul'=> $request->judul,
                'category_id'=> $request->category_id,
                'content'=> $request->content,
                'gambar'=> 'public/uploads/posts/'.$new_gambar,
                'slug'=> Str::slug($request->judul),
                'status' => $request->status,
                
            ];
        } else{
            $post_data = [
                'judul'=> $request->judul,
                'category_id'=> $request->category_id,
                'content'=> $request->content,
                'slug'=> Str::slug($request->judul),
                'status' => $request->status,
            ];
        }
        
        $post->tags()->sync($request->tags);
        $post->update($post_data);

        return redirect()->route('post.index')->with('status','Artikel Berhasil DiUpdate');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Posts::findorfail($id);
        $post->delete();
        return redirect()->back()->with('status','Artikel Berhasil Dihapus (Trashed Artikel)');
    }
    public function trashed()
    {
        $post = Posts::onlyTrashed()->paginate(8);
        return view('post.hapus', compact('post'));

    }
    public function restore($id)
    {
        $post = Posts::withTrashed()->where('id',$id)->first();
        $post->restore();
        return redirect()->back()->with('status','Artikel Berhasil Direstore (check list artikel) ');

    }
    public function kill($id)
    {
        $post = Posts::withTrashed()->where('id',$id)->first();
        $post->forceDelete();
        return redirect()->back()->with('status','Artikel Berhasil Permanen Hapus');

    }
}

resources/views/post/create.blade.php
@extends('master')

@section('sub-judul','Tambah Artikel')
@section('content')
 
 
 <!-- Content Header (Page header) -->
 

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-header">
            <h3 class="card-title">Form Artikel</h3>

            <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                <i class="fas fa-times"></i>
            </button>
            </div>
        </div>
        <div class="card-body">
            @if (session('status'))
                <div class="alert alert-success">
                    {{session('status')}}
                </div>
            @endif
            <form class="form-horizontal" role="form" action="{{route('post.store')}}" method='post' enctype="multipart/form-data">
            @csrf
                    <div class="card-body">
                        <div class="form-group">
                            <label for="judul" class=" col-form-label">Judul</label>
                        <div >
                            <input type="text" class="form-control @error('judul') is-invalid @enderror" id="judul" name="judul" >
                            @error('judul')<div class="invalid-feedback">{{$message}}</div> @enderror
                        </div>
                        </div>
                        <div class="form-group">
                            <label for="category_id" class=" col-form-label">Pilih Kategori</label>
                        <div >
                            <select class="form-control" id="category_id" name='category_id'>
                                <option value="" holder>Pilih Kategori</option>
                                @foreach($category as $result)
                                <option value="{{$result->id}}">{{$result->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        </div>
                        <div class="form-group">
                            <label>Tags</label>
                            <select class="select2" id='select2' multiple="multiple" data-placeholder="Pilih Tags" style="width: 100%;" name='tags[]'>
                                @foreach($tags as $tag)
                                <option value="{{$tag->id}}">{{$tag->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="content" class=" col-form-label">Isi Konten</label>
                        <div >
                            <textarea type="text"  class="form-control @error('content') is-invalid @enderror" id="content" name="content" ></textarea>
                            @error('content')<div class="invalid-feedback">{{$message}}</div> @enderror
                        </div>
                        </div>
                        @if(auth()->user()->role == 1)
                        <div class="form-group">
                            <div class="row">
                            <legend class="col-form-label col-sm-2 pt-0">Verifikasi Post</legend>
                            <div class="col-sm-10">
                                <div class="form-check">
                                <input class="form-check-input" type="radio" name="status" id="status_aktif" value="1" >
                                <label class="form-check-label" for="status_aktif">
                                    Aktif
                                </label>
                                </div>
                                <div class="form-check">
                                <input class="form-check-input" type="radio" name="status" id="status_tidak" value="0" checked>
                                <label class="form-check-label" for="status_tidak">
                                    Tidak Aktif
                                </label>
                                </div>
                            </div>
                            </div>
                        </div>
                        @endif

                        <div class="form-group">
                            <label for="gambar" class=" col-form-label">Thumbnail</label>
                        <div >
                            <input type="file" class="form-control @error('gambar') is-invalid @enderror" id="gambar" name="gambar" >
                            @error('gambar')<div class="invalid-feedback">{{$message}}</div> @enderror
                        </div>
                        </div>
                    </div>
            </div>
        <!-- /.card-body -->
        <div class="card-footer">
            <a type="button" class="btn btn-secondary" href="{{route('post.index')}}">Tutup</a>
            <button type="submit" class="btn btn-success">Tambah</button>
            </form> 
        </div>
        <!-- /.card-footer-->
        </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->

    <script src="https://cdn.ckeditor.com/ckeditor5/34.1.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create( document.querySelector( '#content' ) )
            .catch( error => {
                console.error( error );
            } );
    </script>

    @endsection

resources/views/post/edit.blade.php
@extends('master')

@section('sub-judul','Edit Artikel')
@section('content')
 
 
 <!-- Content Header (Page header) -->
 

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card card-warning">
        <div class="card-header">
            <h3 class="card-title">Form Artikel</h3>

            <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                <i class="fas fa-times"></i>
            </button>
            </div>
        </div>
        <div class="card-body">
            @if (session('status'))
                <div class="alert alert-success">
                    {{session('status')}}
                </div>
            @endif
            <form class="form-horizontal" role="form" action="{{route('post.update', $post->id)}}" method='post' enctype="multipart/form-data">
            @csrf
            @method('patch')
                    <div class="card-body">
                        <div class="form-group">
                            <label for="judul" class=" col-form-label">Judul</label>
                        <div >
                            <input type="text" class="form-control @error('judul') is-invalid @enderror" id="judul" name="judul" value='{{$post->judul}}' >
                            @error('judul')<div class="invalid-feedback">{{$message}}</div> @enderror
                        </div>
                        </div>
                        <div class="form-group">
                            <label for="category_id" class=" col-form-label">Pilih Kategori</label>
                        <div >
                            <select class="form-control" id="category_id" name='category_id'>
                                <option value="" holder>Pilih Kategori</option>
                                @foreach($category as $result)
                                <option value="{{$result->id}}"
                                        @if($post->category_id == $result->id)
                                        selected
                                        @endif                          
                                >{{$result->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        </div>
                        <div class="form-group">
                            <label>Tags</label>
                            <select class="select2" id='select2' multiple="multiple" data-placeholder="Pilih Tags" style="width: 100%;" name='tags[]'>
                                @foreach($tags as $tag)
                                <option value="{{$tag->id}}"
                                    @foreach($post->tags as $value)
                                        @if($tag->id == $value->id)
                                        selected
                                        @endif                                
                                    @endforeach
                                >{{$tag->name}}
                                </option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="content" class=" col-form-label">Isi Konten</label>
                        <div >
                            <textarea type="text" class="form-control" id="content" name="content" >{{$post->content}}</textarea>
                        </div>
                        </div>
                        @if(auth()->user()->role == 1)
                        <fieldset class="form-group">
                            <div class="row">
                            <legend class="col-form-label col-sm-2 pt-0">Verifikasi Post</legend>
                            <div class="col-sm-10">
                                <div class="form-check">
                                <input class="form-check-input" type="radio" name="status" id="status_aktif" value="1" @if( $post->status == '1') checked @endif>
                                <label class="form-check-label" for="status_aktif">
                                    Aktif
                                </label>
                                </div>
                                <div class="form-check">
                                <input class="form-check-input" type="radio" name="status" id="status_tidak" value="0" @if( $post->status == '0') checked @endif>
                                <label class="form-check-label" for="status_tidak">
                                    Tidak Aktif
                                </label>
                                </div>
                            </div>
                            </div>
                        </fieldset>
                        @endif

                        <div class="form-group">
                            <label for="gambar" class=" col-form-label">Thumbnail</label>
                        <div >
                            <input type="file" class="form-control @error('gambar') is-invalid @enderror" id="gambar" name="gambar" >
                            @error('gambar')<div class="invalid-feedback">{{$message}}</div> @enderror
                        </div>
                        </div>
                    </div>
            </div>
        <!-- /.card-body -->
        <div class="card-footer">
            <a type="button" class="btn btn-secondary" href="{{route('post.index')}}">Tutup</a>
            <button type="submit" class="btn btn-success">Tambah</button>
            </form> 
        </div>
        <!-- /.card-footer-->
        </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->

    <script src="https://cdn.ckeditor.com/ckeditor5/34.1.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create( document.querySelector( '#content' ) )
            .catch( error => {
                console.error( error );
            } );
    </script>

    @endsection

resources/views/post/hapus.blade.php
@extends('master')

@section('sub-judul','Trashed Artikel')
@section('content')
 
 
 <!-- Content Header (Page header) -->
 

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">Tabel Artikel</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body">
        @if (session('status'))
          <div class="alert alert-success">
              {{session('status')}}
          </div>
        @endif

            <!-- Button trigger modal -->
            <div class="table-responsive">
                <table id="dataartikel" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>No</th>
                    <th>Judul Artikel</th>
                    <th>Kategori</th>
                    <th>Tags</th>
                    <th>Gambar</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                
                @foreach($post as $result => $hasil)
                <tr>
                    <td>{{$result + $post->firstitem()}}</td>
                    <td> {{$hasil->judul}} </td>
                    <td> {{$hasil->category->name}} </td>
                    <td> 
                        @foreach($hasil->tags as $tag)
                        <span class=" badge badge-primary">{{$tag->name}}</span>
                        @endforeach                      
                    </td>
                    <td><img src="{{asset($hasil->gambar)}}" class="img-fluid" style="width:100px"></td>
                    <td >
                        <form action="{{route('post.kill', $hasil->id)}}" method="POST">
                          @csrf 
                          @method('delete')
                        <a type="button" class="btn btn-warning" href="{{route('post.restore', $hasil->id)}}">Restore</a>
                        <button type="submit" class="btn btn-danger" onclick="return confirm('data akan dihapus...')">Hapus</button>
                        </form>
                    </td>
                </tr>
                @endforeach
                </tbody>
                </table>
              </div>
                
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
        {{$post->links('pagination::bootstrap-4')}}
        </div>
        <!-- /.card-footer-->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->

    @endsection

resources/views/post/index.blade.php
@extends('master')

@section('sub-judul','Artikel')
@section('content')
 
 
 <!-- Content Header (Page header) -->
 

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">Tabel Artikel</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body">
        @if (session('status'))
          <div class="alert alert-success">
              {{session('status')}}
          </div>
        @endif

            <!-- Button trigger modal -->
            <a type="button" class="btn btn-primary" href="{{route('post.create')}}">Tambah Artikel</a>
            <div class="table-responsive">
                <table id="dataartikel" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>No</th>
                    <th>Judul Artikel</th>
                    <th>Kategori</th>
                    <th>Tags</th>
                    <th>Penulis</th>
                    <th>Gambar</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                
                @foreach($post as $result => $hasil)
                <tr>
                    <td>{{$result + $post->firstitem()}}</td>
                    <td> {{$hasil->judul}} </td>
                    <td> {{$hasil->category->name}} </td>
                    <td> 
                        @foreach($hasil->tags as $tag)
                        <span class=" badge badge-primary">{{$tag->name}}</span>
                        @endforeach                      
                    </td>
                    <td> {{$hasil->users->name}} </td>
                    <td><img src="{{asset($hasil->gambar)}}" class="img-fluid" style="width:100px"></td>
                    @if ($hasil->status == 1)
                        <td><span class="badge badge-success">Aktif</span></td>
                    @else 
                      <td><span class="badge badge-danger">Tidak Aktif</span></td>
                    @endif

                    <td >
                        <form action="{{route('post.destroy', $hasil->id)}}" method="POST">
                          @csrf 
                          @method('delete')
                        <a type="button" class="btn btn-warning" href="{{route('post.edit', $hasil->id)}}">Ubah</a>
                        <button type="submit" class="btn btn-danger" onclick="return confirm('data akan dihapus...')" >Hapus</button>
                        </form>
                    </td>
                </tr>
                @endforeach
                </tbody>
                </table>
              </div>
                
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
        {{$post->links('pagination::bootstrap-4')}}
        </div>
        <!-- /.card-footer-->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->

    @endsection