routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\KaryawanController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['auth','CheckRole:1']], function(){
    Route::get('/post/trashed',[PostController::class, 'trashed'])->name('post.trashed');
    Route::get('/post/restore/{id}',[PostController::class, 'restore'])->name('post.restore');
    Route::delete('/post/kill/{id}',[PostController::class, 'kill'])->name('post.kill');
    

    Route::resource('user', UserController::class);
    Route::resource('karyawan', KaryawanController::class);
    Route::post('/karyawan/images',[KaryawanController::class, 'image_upload'])->name('karyawan.image_upload');

});

Route::group(['middleware' => ['auth','CheckRole:1,2,3']], function(){
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::resources([
        'post' => PostController::class,
        'tag' => TagController::class,
        'category' => CategoryController::class,
    ]);
});


Route::get('/',[BlogController::class, 'index']);
Route::get('/berita-sejahtera',[BlogController::class, 'berita'])->name('berita.utama') ;
Route::get('/berita-sejahtera/list/{category}',[BlogController::class, 'category_berita'])->name('berita.category');
Route::get('/berita-sejahtera/search',[BlogController::class, 'search_berita'])->name('berita.search');
Route::get('/berita-sejahtera/{slug}',[BlogController::class, 'isi_berita'])->name('berita.isi');

app/Models/Karyawan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Karyawan extends Model
{
    protected $fillable = ['judul','category','content'];
    protected $table = 'karyawan';
    use HasFactory;
}

app/Http/Controllers/KaryawanController.php
<?php

namespace App\Http\Controllers;
use App\Models\Karyawan;
use illuminate\Support\Str;

use Illuminate\Http\Request;

class KaryawanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Karyawan $karyawan )
    {
        $karyawan = $karyawan->latest()->paginate(8);
        return view('karyawan.index', compact('karyawan'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('karyawan.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'judul' => 'required|min:3',
            'category' => 'required',
            'content' => 'required',
        ]);
        $karyawan = Karyawan::create([
            'judul'=> $request->judul,
            'category'=> $request->category,
            'content'=> $request->content,

        ]);
        return redirect()->route('karyawan.index')->with('status','Informasi Berhasil Ditambahkan');
    }
    public function image_upload(Request $request)
    { 
        if ($request->hasFile('upload')){
        $originName = $request->file('upload')-> getClientOriginalName();
        $fileName = pathinfo($originName,PATHINFO_FILENAME);
        $extension = $request->file('upload')-> getClientOriginalExtension();
        $fileName = $fileName.'_'.time().'.'.$extension;

        $request->file('upload')->move(public_path('media'),$fileName);

        $url = asset('media/'.$fileName);
        return response()->json([
            'fileName' => $fileName, 'uploaded'=>1, 'url'=>$url
        ]);
        }

       
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $karyawan = Karyawan::findorfail($id);
        return view('karyawan.show', compact('karyawan'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $karyawan = Karyawan::findorfail($id);
        return view('karyawan.edit', compact('karyawan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // dd($request);
        $this->validate($request,[
            'judul' => 'required|min:3',
            'category' => 'required',
            'content' => 'required',
        ]);
        $karyawan = Karyawan::findorfail($id);
        // dd($karyawan);
        $karyawan_data = [
            'judul'=> $request->judul,
            'category'=> $request->category,
            'content'=> $request->content,
        ];

        $karyawan->update($karyawan_data);

        return redirect()->route('karyawan.index')->with('status','Informasi Berhasil di Update');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $karyawan = Karyawan::findorfail($id);
        $karyawan->delete();

        return redirect()->back()->with('status','Kategori Berhasil Dihapus');
    }
}

resources/views/karyawan/create.blade.php
@extends('master')

@section('sub-judul','Tambah informasi')
@section('content')
 
 
 <!-- Content Header (Page header) -->
 

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-header">
            <h3 class="card-title">Form Artikel Office</h3>

            <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                <i class="fas fa-times"></i>
            </button>
            </div>
        </div>
        <div class="card-body">
            @if (session('status'))
                <div class="alert alert-success">
                    {{session('status')}}
                </div>
            @endif
            <form class="form-horizontal" role="form" action="{{route('karyawan.store')}}" method='post' enctype="multipart/form-data">
            @csrf
                    <div class="card-body">
                        <div class="form-group">
                            <label for="judul" class=" col-form-label">Judul</label>
                        <div >
                            <input type="text" class="form-control @error('judul') is-invalid @enderror" id="judul" name="judul" >
                            @error('judul')<div class="invalid-feedback">{{$message}}</div> @enderror
                        </div>
                        </div>
                        <div class="form-group">
                            <label for="category" class=" col-form-label">Pilih Kategori</label>
                        <div >
                            <select class="form-control" id="category" name='category'>
                                <option value="" holder>Pilih Kategori</option>
                                <option value="Job Desc">Job Desc</option>
                                <option value="SOP">SOP</option>
                                <option value="Laporan">Laporan</option>
                            </select>
                        </div>
                        </div>
                        
                        <div class="form-group">
                            <label for="content" class=" col-form-label">Isi Konten</label>
                        <div >
                            <textarea type="text"  class="form-control @error('content') is-invalid @enderror" id="content" name="content" ></textarea>
                            @error('content')<div class="invalid-feedback">{{$message}}</div> @enderror
                        </div>
                        </div>
                    </div>
            </div>
        <!-- /.card-body -->
        <div class="card-footer">
            <a type="button" class="btn btn-secondary" href="{{route('karyawan.index')}}">Tutup</a>
            <button type="submit" class="btn btn-success">Tambah</button>
            </form> 
        </div>
        <!-- /.card-footer-->
        </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->

    <script src="https://cdn.ckeditor.com/ckeditor5/34.1.0/classic/ckeditor.js"></script>
    <script>


        ClassicEditor
            .create( document.querySelector( '#content' ), {
               ckfinder:{
                    uploadUrl: '{{route("karyawan.image_upload")."?_token=".csrf_token()}}',  
                },
                
                // ...
            } )                                                                     
            .catch( error => {
                console.error( error );
            } );
    </script>

    @endsection

resources/views/karyawan/edit.blade.php
@extends('master')

@section('sub-judul','Edit Karyawan')
@section('content')
 
 
 <!-- Content Header (Page header) -->
 

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card card-warning">
        <div class="card-header">
            <h3 class="card-title">Form Edit Karyawan</h3>

            <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                <i class="fas fa-times"></i>
            </button>
            </div>
        </div>
        <div class="card-body">
            @if (session('status'))
                <div class="alert alert-success">
                    {{session('status')}}
                </div>
            @endif
            <form class="form-horizontal" role="form" action="{{route('karyawan.update', $karyawan->id)}}" method='post' enctype="multipart/form-data">
            @csrf
            @method('patch')
                    <div class="card-body">
                        <div class="form-group">
                            <label for="judul" class=" col-form-label">Judul</label>
                        <div >
                            <input type="text" class="form-control @error('judul') is-invalid @enderror" id="judul" name="judul" value='{{$karyawan->judul}}' >
                            @error('judul')<div class="invalid-feedback">{{$message}}</div> @enderror
                        </div>
                        </div>
                        <div class="form-group">
                            <label for="category" class=" col-form-label">Pilih Kategori</label>
                        <div >
                            <select class="form-control" id="category" name='category'>
                                <option value="" holder>Pilih Kategori</option>
                                <option value="Job Desc"  @if($karyawan->category == "Job Desc") selected @endif >Job Desc</option>
                                <option value="SOP" @if($karyawan->category == "SOP") selected @endif>SOP</option>
                                <option value="Laporan" @if($karyawan->category == "Laporan") selected @endif>Laporan</option>
                            </select>
                        </div>
                        </div>
                        <div class="form-group">
                            <label for="content" class=" col-form-label">Isi Konten</label>
                        <div >
                            <textarea type="text" class="form-control" id="content" name="content" >{!!$karyawan->content!!}</textarea>
                        </div>
                        </div>

                       
                    </div>
            </div>
        <!-- /.card-body -->
        <div class="card-footer">
            <a type="button" class="btn btn-secondary" href="{{route('karyawan.index')}}">Tutup</a>
            <button type="submit" class="btn btn-success">Tambah</button>
            </form> 
        </div>
        <!-- /.card-footer-->
        </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->

    <script src="https://cdn.ckeditor.com/ckeditor5/34.1.0/classic/ckeditor.js"></script>
    <script>
       ClassicEditor
            .create( document.querySelector( '#content' ), {
               ckfinder:{
                    uploadUrl: '{{route("karyawan.image_upload")."?_token=".csrf_token()}}',  
                },
                // ...
            } )                                                                     
            .catch( error => {
                console.error( error );
            } );
    </script>

    @endsection

resources/views/karyawan/index.blade.php
@extends('master')

@section('sub-judul','Informasi')
@section('content')
 
 
 <!-- Content Header (Page header) -->
 

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">Office Information</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body">
        @if (session('status'))
          <div class="alert alert-success">
              {{session('status')}}
          </div>
        @endif

            <!-- Button trigger modal -->
            @if(auth()->user()->role == 1)
            <a type="button" class="btn btn-primary" href="{{route('karyawan.create')}}">Tambah Artikel</a>
            @endif
                <table id="datasantri" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>No</th>
                    <th>Judul</th>
                    <th>Kategori</th>
                    <th width="35%">Action</th>
                </tr>
                </thead>
                <tbody>
                
                @foreach($karyawan as $result => $hasil)
                <tr>
                    <td>{{$result + $karyawan->firstitem()}}</td>
                    <td> {{$hasil->judul}} </td>
                    <td> {{$hasil->category}} </td>
                    <td >
                        <form action="{{route('karyawan.destroy', $hasil->id)}}" method="POST">
                          @csrf 
                          @method('delete')
                          <a type="button" class="btn btn-primary" href="{{route('karyawan.show', $hasil->id)}}">Lihat</a>
                        <a type="button" class="btn btn-warning" href="{{route('karyawan.edit', $hasil->id)}}">Ubah</a>
                        @if(auth()->user()->role == 1)
                        <button type="submit" class="btn btn-danger" onclick="return confirm('data akan dihapus...')" >Hapus</button>
                        @endif  
                      </form>
                    </td>
                </tr>
                @endforeach
                </tbody>
                </table>
                
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
        {{$karyawan->links('pagination::bootstrap-4')}}
        </div>
        <!-- /.card-footer-->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->



    @endsection

resources/views/karyawan/show.blade.php
@extends('master')

@section('sub-judul','Office Info')
@section('content')
 
 
 <!-- Content Header (Page header) -->
 

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title"> {{$karyawan->category}}</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body">
        <h1 > {{$karyawan->judul}}</h1><br>
        {!! $karyawan -> content !!}
                
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
        <a type="button" class="btn btn-secondary" href="{{route('karyawan.index')}}">Tutup</a>
        </div>
        <!-- /.card-footer-->
      </div>

      <!-- /.card -->

    </section>
    <!-- /.content -->



    @endsection