routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\KaryawanController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['auth','CheckRole:1']], function(){
    Route::get('/post/trashed',[PostController::class, 'trashed'])->name('post.trashed');
    Route::get('/post/restore/{id}',[PostController::class, 'restore'])->name('post.restore');
    Route::delete('/post/kill/{id}',[PostController::class, 'kill'])->name('post.kill');
    

    Route::resource('user', UserController::class);
    Route::resource('karyawan', KaryawanController::class);
    Route::post('/karyawan/images',[KaryawanController::class, 'image_upload'])->name('karyawan.image_upload');

});

Route::group(['middleware' => ['auth','CheckRole:1,2,3']], function(){
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::resources([
        'post' => PostController::class,
        'tag' => TagController::class,
        'category' => CategoryController::class,
    ]);
});


Route::get('/',[BlogController::class, 'index']);
Route::get('/berita-sejahtera',[BlogController::class, 'berita'])->name('berita.utama') ;
Route::get('/berita-sejahtera/list/{category}',[BlogController::class, 'category_berita'])->name('berita.category');
Route::get('/berita-sejahtera/search',[BlogController::class, 'search_berita'])->name('berita.search');
Route::get('/berita-sejahtera/{slug}',[BlogController::class, 'isi_berita'])->name('berita.isi');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;
use App\Models\User;
use Illuminate\Support\Str;



use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = User::paginate(10);
        return view('user.index', compact('user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required|min:3|max:99',
            'email' => 'required|email',
            'role' => 'required',
            'password' => 'required|min:6',

        ]);

        $user = User::create([
            'name'=> $request->name,
            'email'=> $request->email,
            'role'=> $request->role,
            'password'=>bcrypt($request->password),

        ]);
        return redirect()->back()->with('status','User Berhasil Ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findorfail($id);
        return view('user.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name' => 'min:3|max:99',
            'email' => 'email',
        ]);
        $user_data = [
            'name'=> $request->name,
            'email'=> $request->email,
            'role'=> $request->role,
            'password'=>bcrypt($request->password),
        ];

        User::whereid($id)->update($user_data);
        return redirect()->route('user.index')->with('status','User Berhasil Diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findorfail($id);
        $user->delete();

        return redirect()->back()->with('status','User Berhasil Dihapus');
    }
}

resources/views/user/edit.blade.php
@extends('master')

@section('sub-judul','Edit User')
@section('content')


<section class="content">

<!-- Default box -->
<div class="card card-warning">
  <div class="card-header">
    <h3 class="card-title">Edit User</h3>

    <div class="card-tools">
      <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
        <i class="fas fa-minus"></i>
      </button>
      <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
        <i class="fas fa-times"></i>
      </button>
    </div>
  </div>
  <div class="card-body">
    @if (session('status'))
        <div class="alert alert-success">
            {{session('status')}}
        </div>
    @endif
    <form class="form-horizontal" role="form" action="{{route('user.update', $user->id)}}" method='POST' enctype="multipart/form-data">
      @csrf
      @method('patch')
            <div class="card-body">
            <div class="form-group">
                    <label for="name" class=" col-form-label">Nama User</label>
                <div >
                    <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{$user->name }}">
                    @error('name')<div class="invalid-feedback">{{$message}}</div> @enderror
                </div>
                <div class="form-group">
                    <label for="email" class=" col-form-label">Email</label>
                <div >
                    <input type="email" class="form-control @error('email') is-invalid @enderror" id="email" name="email" value="{{$user->email }}">
                    @error('email')<div class="invalid-feedback">{{$message}}</div> @enderror
                </div>
                <div class="form-group">
                            <label for="role" class=" col-form-label">Pilih Role</label>
                        <div >
                            <select class="form-control" id="role" name='role'>
                                <option value="" holder>Pilih Role</option>
                                <option value="1" @if( $user->role == '1') selected @endif>Administrator</option>
                                <option value="2" @if( $user->role == '2') selected @endif>Author</option>
                                <option value="3" @if( $user->role == '3') selected @endif>User</option>
                            </select>
                        </div>
                        </div>
                <div class="form-group">
                    <label for="password" class=" col-form-label">Password</label>
                <div >
                    <input type="password" class="form-control @error('password') is-invalid @enderror" id="password" name="password" placeholder="Tulis disini....">
                    @error('password')<div class="invalid-feedback">{{$message}}</div> @enderror
                </div>
                </div>
            </div>
    </div>
  <!-- /.card-body -->
  <div class="card-footer">
    <a type="button" class="btn btn-secondary" href="{{route('user.index')}}">Tutup</a>
    <button type="submit" class="btn btn-success">Update</button>
    </form> 
  </div>
  <!-- /.card-footer-->
</div>
<!-- /.card -->

</section>

@endsection

resources/views/user/index.blade.php
@extends('master')

@section('sub-judul','Pengaturan User')
@section('content')
 
 
 <!-- Content Header (Page header) -->
 

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">Tabel User</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body">
        @if (session('status'))
          <div class="alert alert-success">
              {{session('status')}}
          </div>
        @endif

            <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
            Tambah User
            </button>
                <table id="datasantri" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>No</th>
                    <th>Nama User</th>
                    <th>Email</th>
                    <th>Role</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                
                @foreach($user as $result => $hasil)
                <tr>
                    <td>{{$result + $user->firstitem()}}</td>
                    <td> {{$hasil->name}} </td>
                    <td> {{$hasil->email}} </td>
                    <td> 
                         @if($hasil->role == 1)
                         <span class=" badge badge-warning">Administrator </span>
                         @elseif($hasil->role == 2)   
                         <span class=" badge badge-success">Author  </span>
                         @else
                         <span class=" badge badge-info">User </span>
                         @endif
                    </td>
                    <td >
                        <form action="{{route('user.destroy', $hasil->id)}}" method="POST">
                          @csrf 
                          @method('delete')
                        <a type="button" class="btn btn-warning" href="{{route('user.edit', $hasil->id)}}">Ubah</a>
                        <button type="submit" class="btn btn-danger" onclick="return confirm('data akan dihapus...')" >Hapus</button>
                        </form>
                    </td>
                </tr>
                @endforeach
                </tbody>
                </table>
                
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
        {{$user->links('pagination::bootstrap-4')}}
        </div>
        <!-- /.card-footer-->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->


<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Tambah User</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <form class="form-horizontal" role="form" action="{{route('user.store')}}" method='POST' enctype="multipart/form-data">
      @csrf
            <div class="card-body">
                <div class="form-group">
                    <label for="name" class=" col-form-label">Nama User</label>
                <div >
                    <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name" placeholder="Tulis disini....">
                    @error('name')<div class="invalid-feedback">{{$message}}</div> @enderror
                </div>
                <div class="form-group">
                    <label for="email" class=" col-form-label">Email</label>
                <div >
                    <input type="email" class="form-control @error('email') is-invalid @enderror" id="email" name="email" placeholder="Tulis disini....">
                    @error('email')<div class="invalid-feedback">{{$message}}</div> @enderror
                </div>
                <div class="form-group">
                            <label for="role" class=" col-form-label">Pilih Role</label>
                        <div >
                            <select class="form-control" id="role" name='role'>
                                <option value="" holder>Pilih Role</option>
                                <option value="1">Administrator</option>
                                <option value="2">Author</option>
                                <option value="3">User</option>
                            </select>
                        </div>
                        </div>
                <div class="form-group">
                    <label for="password" class=" col-form-label">Password</label>
                <div >
                    <input type="password" class="form-control @error('password') is-invalid @enderror" id="password" name="password" placeholder="Tulis disini....">
                    @error('password')<div class="invalid-feedback">{{$message}}</div> @enderror
                </div>
                </div>
            </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Tutup</button>
        <button type="submit" class="btn btn-success">Simpan</button>
        </form> 
      </div>
    </div>
  </div>
</div>
    @endsection